package rahulShetty;

public class ExceptionDemo {

		
		int a = 4;
		int b = 2;
		int c = 0;
		
		int k = b/c;
		
		public void getData() {
			try {
				System.out.println(k);
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
		public static void main(String[] args) {
			
		ExceptionDemo ed= new ExceptionDemo();
		ed.getData();
			
		}
		
		
		

}
