package rahulShetty;

public class ExceptionDemo {

		
	
		public static void main(String[] args) {
			
			try {
				int a = 4;
				int b = 2;
				int c = 0;
				
				int k = b/c;
			} 
			
			catch(ArithmeticException e){
				System.out.println("I Catched Arithmetic Exceptions");
			}
			
			catch (Exception e) {								
				// Use print only when you want to continue				
				System.out.println("I Catched  Exceptions");
			}
		
	
			
		}
		
		
		

}
